language: cpp
cache:
  ccache: true

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

install:
  - eval "${MATRIX_EVAL}"
#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -qq update; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then sudo chown -R $(whoami) /usr/local; fi
#  # Avoid bug on CI with OSX, see https://github.com/travis-ci/travis-ci/issues/8552
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install ccache; export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

script:
  - cmake --version
  - cmake -H. -Bbuild
  - cmake --build build --target all
  - cmake --build build --target test
