name: C++ CI

on: [push, pull_request]

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_alpine
    - name: Build project
      run: make --directory=ci devel_alpine
    - name: Test project
      run: make --directory=ci test_alpine
    - name: Test Install project
      run: make --directory=ci test_install_alpine
  build-archlinux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_archlinux
    - name: Build project
      run: make --directory=ci devel_archlinux
    - name: Test project
      run: make --directory=ci test_archlinux
    - name: Test Install project
      run: make --directory=ci test_install_archlinux
  build-centos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_centos
    - name: Build project
      run: make --directory=ci devel_centos
    - name: Test project
      run: make --directory=ci test_centos
    - name: Test Install project
      run: make --directory=ci test_install_centos
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_debian
    - name: Build project
      run: make --directory=ci devel_debian
    - name: Test project
      run: make --directory=ci test_debian
    - name: Test Install project
      run: make --directory=ci test_install_debian
  build-fedora:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_fedora
    - name: Build project
      run: make --directory=ci devel_fedora
    - name: Test project
      run: make --directory=ci test_fedora
    - name: Test Install project
      run: make --directory=ci test_install_fedora
  build-opensuse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_opensuse
    - name: Build project
      run: make --directory=ci devel_opensuse
    - name: Test project
      run: make --directory=ci test_opensuse
    - name: Test Install project
      run: make --directory=ci test_install_opensuse
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build env image
      run: make --directory=ci env_ubuntu
    - name: Build project
      run: make --directory=ci devel_ubuntu
    - name: Test project
      run: make --directory=ci test_ubuntu
    - name: Test Install project
      run: make --directory=ci test_install_ubuntu

  # Building using the github runner environement directly.
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cmake --build build --config Release --target test -v
    - name: Install
      run: cmake --build build --config Release --target install -v -- DESTDIR=install
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cmake --build build --config Release --target test -v
    - name: Install
      run: cmake --build build --config Release --target install -v
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /maxcpucount
